### ISSUE TITLE
SPL in SDP mode not recognized by UUU

### ISSUE THREAD

**Issue by ondrejhennel** [TechNexion/u-boot-tn-imx#15]
I ran into this issue while trying to use UUU to flash a pico-imx7d SOM. After booting up into serial download mode and connecting the USB cable, UUU recognizes the SOM and is able to boot SPL. SPL goes into SDP mode, but it is not recognized by UUU.

I found out that the problem is the wrong combination of VID and PID. UUU has a predefined set of VID:PID pairs that it should recognize. In u-boot, the VID and PID for usb gadget is defined using defconfig. for example in `configs/pico-imx7d_spl_defconfig`.
```
CONFIG_USB_GADGET_VENDOR_NUM=0x0525
CONFIG_USB_GADGET_PRODUCT_NUM=0xa4a5
```

However, UUU needs some way to recognize between SDP mode in SPL and fastboot mode in u-boot proper to apply the correct configuration. This is achieved by setting a different PID when in SPL using this function in `arch/arm/mach-imx/spl.c`.
```C
int g_dnl_bind_fixup(struct usb_device_descriptor *dev, const char *name)
{
	put_unaligned(CONFIG_USB_GADGET_PRODUCT_NUM + 0xfff, &dev->idProduct);
	return 0;
}
```

`g_dnl_bind_fixup` is called before binding a g_dnl USB gadget, which is used to enter SDP mode in SPL.

In e330a88, which comes from u-boot-imx, VIDs and PIDs are changed to use the Freescale VID (`0x1fc9`) and avoid collisions with other devices. The new PIDs are `0x151` for SPL SDP and `0x152` for fastboot in u-boot proper. Defconfig is changed like this:
```
CONFIG_USB_GADGET_VENDOR_NUM=0x1fc9
CONFIG_USB_GADGET_PRODUCT_NUM=0x0152
```
And `arch/arm/mach-imx/spl.c` is changed like this:
```C
int g_dnl_bind_fixup(struct usb_device_descriptor *dev, const char *name)
{
	put_unaligned(0x0151, &dev->idProduct);
	return 0;
}
```
The new VID:PID pairs are also added to UUU from version 1.4.182 upwards. The old ones are kept for backwards compatibility.

In this commit, only the defconfig files maintained by imx are changed. The others still use the old VID and PID. This works fine in u-boot proper, because the old IDs are still supported by UUU. However, because the `arch/arm/mach-imx/spl.c` file is common for all imx devices, the PID is replaced with the new one in SPL. This results in a combination of VID `0x0525` (old value) and PID `0x0151` (new value). This combination is not recognized by UUU.

I think the correct way to fix this is to update the defconfigs of all technexion boards to use the new values. This also avoids possible future collisions, which is the reason for the commit e330a88. If you agree, i am willing to submit a PR.

I am using imx UUU. The technexion fork of UUU is based on an older version which does not recognize the new VID:PID pairs so it would also need to be updated.

This problem is also present in u-boot-imx and in mainline u-boot. I submitted the issue here, because I think it should probably be fixed here and then trickle up to mainline.

**Comment by ondrejhennel** [comment]
This issue has been open for 3 months with no response. Could someone please pick this up? Thanks.

**Comment by ray-chang** [comment]
@ondrejhennel 

Thanks for the feedback.
I've modified it on u-boot v2022.04. But the binaries we use on the uuu tool won't be updated yet. Because there are still a lot of problems, and it's still usable.
https://github.com/TechNexion/u-boot-tn-imx/commit/e330b7a45dc7a2bfef9caeac0df4450f452a7ddd

BR,
Ray
