### ISSUE TITLE
Copy error, 'u-boot.img' are the same file

### ISSUE THREAD

**Issue by JeanPhilippeLebel** [TechNexion/u-boot-tn-imx#17]
We are in the process of upgrading our build system to Kirkstone and I'm having a weird issue compiling the uboot

ERROR: u-boot-tn-imx-2022.04-r0 do_deploy: ExecutionError('/home/dev/build-tep0700-alfredos/tmp/work/tep1_imx7-poky-linux-gnueabi/u-boot-tn-imx/2022.04-r0/temp/run.do_deploy.349', 1, None, None)
ERROR: Logfile of failure stored in: /home/dev/build-tep0700-alfredos/tmp/work/tep1_imx7-poky-linux-gnueabi/u-boot-tn-imx/2022.04-r0/temp/log.do_deploy.349
Log data follows:
| DEBUG: Executing python function sstate_task_prefunc
| DEBUG: Python function sstate_task_prefunc finished
| DEBUG: Executing shell function do_deploy
**| cp: '/home/dev/build-tep0700-alfredos/tmp/work/tep1_imx7-poky-linux-gnueabi/u-boot-tn-imx/2022.04-r0/deploy-u-boot-tn-imx/u-boot.img' and '/home/dev/build-tep0700-alfredos/tmp/work/tep1_imx7-poky-linux-gnueabi/u-boot-tn-imx/2022.04-r0/deploy-u-boot-tn-imx/u-boot.img' are the same file**

This doesn't make sense to me and before investigating that particular issue I wanted to know if you have an idea of what can cause that.

Thanks

**Comment by ray-chang** [comment]
@JeanPhilippeLebel 

Thanks for the feedback.
I looked at do_deploy function of u-boot-tn-imx and only found a `cp` command. It is located at:
https://github.com/Freescale/meta-freescale/commit/92acf99a6124df0d2e10bf10f296962ab9383ba1#diff-4ed0c53a5d3b99caafddc024584c01e4bef81dacf72f98a3c4b1f77278cda321

However, we didn't have this problem on our side.
You can use the `cleanall` command and then rebuild it.
> bitbake u-boot-tn-imx -c cleanall

**Comment by JeanPhilippeLebel** [comment]
Thanks for pointing me to that code.

The culprit seems to be located here https://github.com/Freescale/meta-freescale/blob/5814ce5822d4ea511311c9732b18b0aad87f782e/recipes-bsp/u-boot/u-boot-imx_2023.04.bb#L15

The default name is set to "". Interestingly enough, my MACHINE is set to "tep1-imx7" but it seems I'm missing something else. (I'm working from a custom distro file so maybe there is a setting missing somewhere?)

Thanks,
