### ISSUE TITLE
‘__bss_start’ undeclared

### ISSUE THREAD

**Issue by prchal** [TechNexion/u-boot-tn-imx#29]
Hi,
while compiling u-boot + SPL it runs to error in SPL part:
`
  CC      spl/board/technexion/pico-imx8mm/pico-imx8mm_spl.o
board/technexion/pico-imx8mm/pico-imx8mm_spl.c: In function ‘board_init_f’:
board/technexion/pico-imx8mm/pico-imx8mm_spl.c:334:9: error: ‘__bss_start’ undeclared (first use in this function); did you mean ‘va_start’?
  memset(__bss_start, 0, __bss_end - __bss_start);
         ^~~~~~~~~~~
         va_start
`
Compiler is:
`
aarch64-linux-gnu-gcc (Linaro GCC 7.5-2019.12) 7.5.0
`

**Comment by ray-chang** [comment]
@prchal 

Thanks for the feedback!
The pico-imx8mm is not ready on the tn-imx_v2024.04_6.6.36_2.1.0. Currently, only edm-g-imx8mp, edm-g-imx8mm and axon-imx93 are supported. Please wait patiently. It is advisable to contact TechNexion sales if there are business considerations.

Here's the link to the release again for your reference:
https://github.com/TechNexion/u-boot-tn-imx/releases/tag/tn-scarthgap_6.6.36_2.1.0_20241014
If you have any other questions or need further assistance, feel free to ask.

BR,
Ray

**Comment by prchal** [comment]
So they are sold empty? I've got one, but nothing on console. How long should I be patient?

**Comment by johnweber** [comment]
They are not sold empty. Each module is preprogrammed with a software loader image that can download and install a demo image from our server.  A display is necessary for this as the loader uses a GUI program to allow the user to select the image to install.

Even if you don't have a display, if the module is new and nothing overwritten in the e.MMC, you should see messages in the console, and should be able to halt U-boot and use 'ums', for example, to load software on the e.MMC over USB.

Please reach out to 'sales@technexion.com' if you require additional support.   We are closing this issue for now, as it seems specific to your use case/toolchain.

Thanks,
John
